/// ISO country codes → display names by language (`en` / `ru` / `es` / `sr`).
const Map<String, Map<String, String>> _countryNames = {
  'en': {
    'RU': 'Russia',
    'US': 'United States',
    'GB': 'United Kingdom',
    'DE': 'Germany',
    'FR': 'France',
    'IT': 'Italy',
    'ES': 'Spain',
    'PL': 'Poland',
    'TR': 'Turkey',
    'KZ': 'Kazakhstan',
    'UA': 'Ukraine',
    'BY': 'Belarus',
    'CN': 'China',
    'JP': 'Japan',
    'KR': 'South Korea',
    'IN': 'India',
    'BR': 'Brazil',
    'CA': 'Canada',
    'AU': 'Australia',
    'CH': 'Switzerland',
    'SE': 'Sweden',
    'NO': 'Norway',
    'FI': 'Finland',
    'CZ': 'Czechia',
    'HU': 'Hungary',
    'AT': 'Austria',
    'NL': 'Netherlands',
    'BE': 'Belgium',
    'PT': 'Portugal',
    'GR': 'Greece',
    'IE': 'Ireland',
    'AE': 'United Arab Emirates',
    'TH': 'Thailand',
    'VN': 'Vietnam',
    'ID': 'Indonesia',
    'MY': 'Malaysia',
    'SG': 'Singapore',
    'GE': 'Georgia',
    'AM': 'Armenia',
    'AZ': 'Azerbaijan',
    'UZ': 'Uzbekistan',
    'EG': 'Egypt',
    'IL': 'Israel',
    'MX': 'Mexico',
    'AR': 'Argentina',
  },
  'ru': {
    'RU': 'Россия',
    'US': 'США',
    'GB': 'Великобритания',
    'DE': 'Германия',
    'FR': 'Франция',
    'IT': 'Италия',
    'ES': 'Испания',
    'PL': 'Польша',
    'TR': 'Турция',
    'KZ': 'Казахстан',
    'UA': 'Украина',
    'BY': 'Беларусь',
    'CN': 'Китай',
    'JP': 'Япония',
    'KR': 'Южная Корея',
    'IN': 'Индия',
    'BR': 'Бразилия',
    'CA': 'Канада',
    'AU': 'Австралия',
    'CH': 'Швейцария',
    'SE': 'Швеция',
    'NO': 'Норвегия',
    'FI': 'Финляндия',
    'CZ': 'Чехия',
    'HU': 'Венгрия',
    'AT': 'Австрия',
    'NL': 'Нидерланды',
    'BE': 'Бельгия',
    'PT': 'Португалия',
    'GR': 'Греция',
    'IE': 'Ирландия',
    'AE': 'ОАЭ',
    'TH': 'Таиланд',
    'VN': 'Вьетнам',
    'ID': 'Индонезия',
    'MY': 'Малайзия',
    'SG': 'Сингапур',
    'GE': 'Грузия',
    'AM': 'Армения',
    'AZ': 'Азербайджан',
    'UZ': 'Узбекистан',
    'EG': 'Египет',
    'IL': 'Израиль',
    'MX': 'Мексика',
    'AR': 'Аргентина',
  },
  'es': {
    'RU': 'Rusia',
    'US': 'Estados Unidos',
    'GB': 'Reino Unido',
    'DE': 'Alemania',
    'FR': 'Francia',
    'IT': 'Italia',
    'ES': 'España',
    'PL': 'Polonia',
    'TR': 'Turquía',
    'KZ': 'Kazajistán',
    'UA': 'Ucrania',
    'BY': 'Bielorrusia',
    'CN': 'China',
    'JP': 'Japón',
    'KR': 'Corea del Sur',
    'IN': 'India',
    'BR': 'Brasil',
    'CA': 'Canadá',
    'AU': 'Australia',
    'CH': 'Suiza',
    'SE': 'Suecia',
    'NO': 'Noruega',
    'FI': 'Finlandia',
    'CZ': 'Chequia',
    'HU': 'Hungría',
    'AT': 'Austria',
    'NL': 'Países Bajos',
    'BE': 'Bélgica',
    'PT': 'Portugal',
    'GR': 'Grecia',
    'IE': 'Irlanda',
    'AE': 'Emiratos Árabes Unidos',
    'TH': 'Tailandia',
    'VN': 'Vietnam',
    'ID': 'Indonesia',
    'MY': 'Malasia',
    'SG': 'Singapur',
    'GE': 'Georgia',
    'AM': 'Armenia',
    'AZ': 'Azerbaiyán',
    'UZ': 'Uzbekistán',
    'EG': 'Egipto',
    'IL': 'Israel',
    'MX': 'México',
    'AR': 'Argentina',
  },
  'sr': {
    'RU': 'Rusija',
    'US': 'Sjedinjene Države',
    'GB': 'Ujedinjeno Kraljevstvo',
    'DE': 'Nemačka',
    'FR': 'Francuska',
    'IT': 'Italija',
    'ES': 'Španija',
    'PL': 'Poljska',
    'TR': 'Turska',
    'KZ': 'Kazahstan',
    'UA': 'Ukrajina',
    'BY': 'Belorusija',
    'CN': 'Kina',
    'JP': 'Japan',
    'KR': 'Južna Koreja',
    'IN': 'Indija',
    'BR': 'Brazil',
    'CA': 'Kanada',
    'AU': 'Australija',
    'CH': 'Švajcarska',
    'SE': 'Švedska',
    'NO': 'Norveška',
    'FI': 'Finska',
    'CZ': 'Češka',
    'HU': 'Mađarska',
    'AT': 'Austrija',
    'NL': 'Holandija',
    'BE': 'Belgija',
    'PT': 'Portugalija',
    'GR': 'Grčka',
    'IE': 'Irska',
    'AE': 'Ujedinjeni Arapski Emirati',
    'TH': 'Tajland',
    'VN': 'Vijetnam',
    'ID': 'Indonezija',
    'MY': 'Malezija',
    'SG': 'Singapur',
    'GE': 'Gruzija',
    'AM': 'Jermenija',
    'AZ': 'Azerbejdžan',
    'UZ': 'Uzbekistan',
    'EG': 'Egipat',
    'IL': 'Izrael',
    'MX': 'Meksiko',
    'AR': 'Argentina',
  },
};

String _lang(String? languageCode) {
  return switch (languageCode) {
    'ru' => 'ru',
    'es' => 'es',
    'sr' => 'sr',
    _ => 'en',
  };
}

String countryDisplayName(String code, {String? languageCode}) {
  final upper = code.toUpperCase();
  final lang = _lang(languageCode);
  return _countryNames[lang]?[upper] ??
      _countryNames['en']?[upper] ??
      upper;
}

List<MapEntry<String, String>> sortedCountries({String? languageCode}) {
  final lang = _lang(languageCode);
  final map = _countryNames[lang] ?? _countryNames['en']!;
  final entries = map.entries.toList()
    ..sort((a, b) => a.value.compareTo(b.value));
  return entries;
}

/// Currency → country/region code for region labels.
const Map<String, String> currencyRegionCode = {
  'RUB': 'RU',
  'USD': 'US',
  'EUR': 'EU',
  'GBP': 'GB',
  'CNY': 'CN',
  'JPY': 'JP',
  'PLN': 'PL',
  'TRY': 'TR',
  'KZT': 'KZ',
  'UAH': 'UA',
  'BYN': 'BY',
  'CHF': 'CH',
  'CAD': 'CA',
  'AUD': 'AU',
  'SEK': 'SE',
  'NOK': 'NO',
  'CZK': 'CZ',
  'HUF': 'HU',
  'INR': 'IN',
  'BRL': 'BR',
};

String regionLabelForCurrency(String currencyCode, {String? languageCode}) {
  final code = currencyRegionCode[currencyCode.toUpperCase()];
  if (code == null) return currencyCode.toUpperCase();
  if (code == 'EU') {
    return switch (languageCode) {
      'ru' => 'Еврозона',
      'es' => 'Eurozona',
      'sr' => 'Evrozona',
      _ => 'Eurozone',
    };
  }
  return countryDisplayName(code, languageCode: languageCode);
}
