import 'package:flutter/material.dart';

/// Curated icon keys for category tags, subcategories, and payment methods.
///
/// Stored as [Tags.iconKey] / [PaymentMethods.iconKey]; resolved via
/// [iconDataForTagKey].
const List<String> curatedTagIconKeys = [
  // Food & drink
  'groceries',
  'dining',
  'restaurant',
  'cafe',
  'coffee',
  'delivery',
  'fastfood',
  'bakery',
  'alcohol',
  'snacks',
  // Transport
  'transport',
  'car',
  'fuel',
  'parking',
  'taxi',
  'bus',
  'train',
  'metro',
  'bike',
  'scooter',
  'flight',
  'repair',
  'tuning',
  // Home & utilities
  'housing',
  'rent',
  'furniture',
  'cleaning',
  'laundry',
  'tools',
  'garden',
  'plant',
  'dacha',
  'utilities',
  'water',
  'gas',
  'wifi',
  'internet',
  // Health & care
  'health',
  'doctor',
  'medications',
  'dentistry',
  'optics',
  'lab',
  'fitness',
  'spa',
  'baby',
  'pets',
  'pet_food',
  // Shopping & lifestyle
  'shopping',
  'clothing',
  'shoes',
  'electronics',
  'devices',
  'beauty',
  'gifts',
  'home_goods',
  // Leisure
  'entertainment',
  'cinema',
  'games',
  'music',
  'streaming',
  'events',
  'hobbies',
  'sports',
  'travel',
  'hotel',
  'map',
  'beach',
  // Work & money
  'work',
  'education',
  'salary',
  'sale',
  'gift',
  'refund',
  'investment',
  'chart',
  'bank',
  'insurance',
  'taxes',
  'charity',
  'freelance',
  'cashback',
  // Payments & tech
  'cash',
  'card',
  'crypto',
  'transfer',
  'ewallet',
  'nfc',
  'qr_code',
  'phone',
  'subscriptions',
  'cloud',
  'lock',
  // Generic
  'other',
  'star',
  'heart',
  'bookmark',
  'calendar',
  'note',
  'camera',
  'key',
];

/// Default [iconKey] for a seeded tag / subcategory [stableKey], if known.
String? defaultIconKeyForStableKey(String stableKey) {
  const map = <String, String>{
    // Top-level expense
    'groceries': 'groceries',
    'transport': 'transport',
    'housing': 'housing',
    'dining': 'dining',
    'health': 'health',
    'entertainment': 'entertainment',
    'shopping': 'shopping',
    'travel': 'travel',
    'utilities': 'utilities',
    // Top-level income
    'salary': 'salary',
    'sale': 'sale',
    'gift': 'gift',
    'refund': 'refund',
    'investment': 'investment',
    'other_income': 'other',
    // Expense subcategories
    'household_supplies': 'home_goods',
    'alcohol': 'alcohol',
    'snacks': 'snacks',
    'pet_food': 'pet_food',
    'baby_food': 'baby',
    'fuel': 'fuel',
    'repair': 'repair',
    'tuning': 'tuning',
    'parking': 'parking',
    'taxi': 'taxi',
    'public_transit': 'metro',
    'rent': 'rent',
    'utilities_bill': 'utilities',
    'furniture': 'furniture',
    'dacha': 'dacha',
    'home_repairs': 'tools',
    'cleaning': 'cleaning',
    'internet': 'internet',
    'restaurant': 'restaurant',
    'cafe': 'cafe',
    'delivery': 'delivery',
    'lab_tests': 'lab',
    'doctor': 'doctor',
    'medications': 'medications',
    'dentistry': 'dentistry',
    'optics': 'optics',
    'cinema': 'cinema',
    'games': 'games',
    'streaming': 'streaming',
    'events': 'events',
    'hobbies': 'hobbies',
    'clothing': 'clothing',
    'electronics': 'electronics',
    'gifts_shopping': 'gifts',
    'home_goods': 'home_goods',
    'beauty': 'beauty',
    'flights': 'flight',
    'hotels': 'hotel',
    'tours': 'map',
    'travel_insurance': 'insurance',
    'visas': 'note',
    // Income subcategories
    'bonus': 'star',
    'overtime': 'calendar',
    'advance': 'salary',
    'personal_items': 'sale',
    'property_sale': 'housing',
    'vehicle_sale': 'car',
    'family_gift': 'gift',
    'friends_gift': 'gift',
    'holiday_gift': 'gift',
    'tax_refund': 'taxes',
    'purchase_refund': 'refund',
    'insurance_refund': 'insurance',
    'dividends': 'investment',
    'interest_income': 'bank',
    'capital_gains': 'chart',
    'freelance': 'freelance',
    'cashback': 'cashback',
    'side_gig': 'work',
  };
  return map[stableKey];
}

/// Default [iconKey] for a seeded payment-method [stableKey].
String? defaultIconKeyForPaymentStableKey(String stableKey) {
  const map = <String, String>{
    'cash': 'cash',
    'card': 'card',
    'crypto': 'crypto',
    'transfer': 'transfer',
    'ewallet': 'ewallet',
  };
  return map[stableKey];
}

IconData? iconDataForTagKey(String? iconKey) {
  if (iconKey == null || iconKey.isEmpty) return null;
  return switch (iconKey) {
    // Food & drink
    'groceries' => Icons.shopping_basket_outlined,
    'dining' => Icons.restaurant_outlined,
    'restaurant' => Icons.restaurant_menu_outlined,
    'cafe' => Icons.local_cafe_outlined,
    'coffee' => Icons.coffee_outlined,
    'delivery' => Icons.delivery_dining_outlined,
    'fastfood' => Icons.fastfood_outlined,
    'bakery' => Icons.bakery_dining_outlined,
    'alcohol' => Icons.wine_bar_outlined,
    'snacks' => Icons.cookie_outlined,
    // Transport
    'transport' => Icons.directions_bus_outlined,
    'car' => Icons.directions_car_outlined,
    'fuel' => Icons.local_gas_station_outlined,
    'parking' => Icons.local_parking_outlined,
    'taxi' => Icons.local_taxi_outlined,
    'bus' => Icons.directions_bus_filled_outlined,
    'train' => Icons.train_outlined,
    'metro' => Icons.subway_outlined,
    'bike' => Icons.pedal_bike_outlined,
    'scooter' => Icons.electric_scooter_outlined,
    'flight' => Icons.flight_outlined,
    'travel' => Icons.flight_outlined,
    'repair' => Icons.car_repair_outlined,
    'tuning' => Icons.tune_outlined,
    // Home & utilities
    'housing' => Icons.home_outlined,
    'rent' => Icons.apartment_outlined,
    'furniture' => Icons.chair_outlined,
    'cleaning' => Icons.cleaning_services_outlined,
    'laundry' => Icons.local_laundry_service_outlined,
    'tools' => Icons.handyman_outlined,
    'garden' => Icons.yard_outlined,
    'plant' => Icons.grass_outlined,
    'dacha' => Icons.cottage_outlined,
    'utilities' => Icons.bolt_outlined,
    'water' => Icons.water_drop_outlined,
    'gas' => Icons.local_fire_department_outlined,
    'wifi' => Icons.wifi_outlined,
    'internet' => Icons.router_outlined,
    // Health & care
    'health' => Icons.local_hospital_outlined,
    'doctor' => Icons.medical_services_outlined,
    'medications' => Icons.medication_outlined,
    'dentistry' => Icons.medical_information_outlined,
    'optics' => Icons.visibility_outlined,
    'lab' => Icons.science_outlined,
    'fitness' => Icons.fitness_center_outlined,
    'spa' => Icons.spa_outlined,
    'baby' => Icons.child_care_outlined,
    'pets' => Icons.pets_outlined,
    'pet_food' => Icons.pets_outlined,
    // Shopping & lifestyle
    'shopping' => Icons.shopping_bag_outlined,
    'clothing' => Icons.checkroom_outlined,
    'shoes' => Icons.hiking_outlined,
    'electronics' => Icons.devices_outlined,
    'devices' => Icons.smartphone_outlined,
    'beauty' => Icons.spa_outlined,
    'gifts' => Icons.card_giftcard_outlined,
    'home_goods' => Icons.kitchen_outlined,
    // Leisure
    'entertainment' => Icons.movie_outlined,
    'cinema' => Icons.theaters_outlined,
    'games' => Icons.sports_esports_outlined,
    'music' => Icons.music_note_outlined,
    'streaming' => Icons.subscriptions_outlined,
    'events' => Icons.event_outlined,
    'hobbies' => Icons.extension_outlined,
    'sports' => Icons.sports_soccer_outlined,
    'hotel' => Icons.hotel_outlined,
    'map' => Icons.map_outlined,
    'beach' => Icons.beach_access_outlined,
    // Work & money
    'work' => Icons.work_outline,
    'education' => Icons.school_outlined,
    'salary' => Icons.payments_outlined,
    'sale' => Icons.sell_outlined,
    'gift' => Icons.card_giftcard_outlined,
    'refund' => Icons.undo_outlined,
    'investment' => Icons.trending_up_outlined,
    'chart' => Icons.show_chart_outlined,
    'bank' => Icons.account_balance_outlined,
    'insurance' => Icons.health_and_safety_outlined,
    'taxes' => Icons.receipt_long_outlined,
    'charity' => Icons.volunteer_activism_outlined,
    'freelance' => Icons.laptop_mac_outlined,
    'cashback' => Icons.savings_outlined,
    // Payments & tech
    'cash' => Icons.money_outlined,
    'card' => Icons.credit_card_outlined,
    'crypto' => Icons.currency_bitcoin,
    'transfer' => Icons.swap_horiz_outlined,
    'ewallet' => Icons.account_balance_wallet_outlined,
    'nfc' => Icons.contactless_outlined,
    'qr_code' => Icons.qr_code_2_outlined,
    'phone' => Icons.phone_android_outlined,
    'subscriptions' => Icons.subscriptions_outlined,
    'cloud' => Icons.cloud_outlined,
    'lock' => Icons.lock_outline,
    // Generic
    'other' => Icons.category_outlined,
    'star' => Icons.star_outline,
    'heart' => Icons.favorite_outline,
    'bookmark' => Icons.bookmark_outline,
    'calendar' => Icons.calendar_today_outlined,
    'note' => Icons.sticky_note_2_outlined,
    'camera' => Icons.photo_camera_outlined,
    'key' => Icons.vpn_key_outlined,
    _ => null,
  };
}
